/// Flutter icons UiElements
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  UiElements
///      fonts:
///       - asset: fonts/UiElements.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class UiElements {
  UiElements._();

  static const _kFontFam = 'UiElements';

  static const IconData home_active = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData home = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData progress = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData trophy = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData trophy_active = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData energy = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData fire = const IconData(0xf525, fontFamily: _kFontFam);
}
